### ISSUE TITLE
Implement CSIS Design

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/csis-theme#5]
Current theming is based on Bootstrap which is a good starting point. The actual CSIS Theme has to implement the [myclimateservice.eu design](https://repository.atosresearch.eu/owncloud/index.php/apps/files/?dir=/CLARITY/WP6%20Dissemination%20and%20Community%20Building/T6.2%20Media%20Production%20and%20Publishing/CSIS%20styles#/CLARITY/WP6%20Dissemination%20and%20Community%20Building/T6.2%20Media%20Production%20and%20Publishing/CSIS%20styles/01_Clarity_Table.png), e.g. custom CSS classes an so on. Developing a Drupal Theme from scratch is probably out of scope but extending an existing one (e.g. the current bootstrap theme) should be possible.

![grafik](https://user-images.githubusercontent.com/1788226/48833372-7c7b0f00-ed7b-11e8-9cc3-6e560af51b25.png)

**Comment by patrickkaleta** [comment]
I talked to Denis about who could implement the CSS. In another Drupal-project we have already someone from Atos working on everything theme-related. And according to Denis we could get him involved in Clarity as well.

**Comment by p-a-s-c-a-l** [comment]
OK. Since the visual styles are created by SCC designers, we should ask them to join the [User Interface Team](https://github.com/orgs/clarity-h2020/teams/user-interface-team) so that we can discuss more efficiently.

**Comment by patrickkaleta** [comment]
Yes, I will contact Andrea and ask who from SCC is responsible for the designs and let you know who to add as a member to the repository.

**Comment by patrickkaleta** [comment]
Talked to Andrea about this. Currently SCC doesn't have a dedicated person for this task, so communications should run through @fgeyer16 for the moment.

**Comment by p-a-s-c-a-l** [comment]
@maesbri please invite Alejandro to join github so that we can assign this task to him ;-)

**Comment by maesbri** [comment]
We finally managed to talk to him yesterday to explain what we need concerning the styling of the CSIS.

He has started working on a local copy of the csis to see the possibilities of what (and how) can be improved according to the proposed style.

**Comment by patrickkaleta** [comment]
@maesbri 
Should Alejandro require a user account for the CSIS, please tell him that he can contact me by mail and I will take care of that.

**Comment by maesbri** [comment]
ok, thanks. 

I think it is better if you just create it. I will forward him the details

**Comment by patrickkaleta** [comment]
@maesbri 
I created the user account for Alejandro and mailed you the details. Please forward them to Alejandro.

**Comment by p-a-s-c-a-l** [comment]
Any progress to be reported here?

**Comment by patrickkaleta** [comment]
@maesbri @DanielRodera How is Alejandro coming along? If I'm not wrong he should be quite familiar with Drupal 8 and theming. Nonetheless we can set up a telco between him, me and @fgeyer16 if that would help move this issue forward.

**Comment by DanielRodera** [comment]
Hi @patrickkaleta , we already have the first version of the new theme. Below you can see some screenshots:

![image](https://user-images.githubusercontent.com/42216407/59679577-852baa80-91cf-11e9-8ef8-5d472df53da4.png)

![image](https://user-images.githubusercontent.com/42216407/59679606-9379c680-91cf-11e9-9ede-0a920a545d5d.png)

![image](https://user-images.githubusercontent.com/42216407/59679635-a42a3c80-91cf-11e9-9bbf-ef219cf3dc38.png)

Alejandro told me to implement the new theme to the CSIS will take about 2 hours (for doing it we should agree a time range when no one works in the CSIS to avoid possible errors). 

These changes can be undo very easily by applying the current theme again (Drupal will respect all the blocks).

If you want to see the new theme before applying to the CSIS we can schedule a telco to show you a demo, or wait for the next developers telco, up to you!

**Comment by patrickkaleta** [comment]
> Alejandro told me to implement the new theme to the CSIS will take about 2 hours (for doing it we should agree a time range when no one works in the CSIS to avoid possible errors).

Great news and a good idea. IMO styling has been neglected long enough, so it should have high priority now. So you and Alejandro just pick a time, when you can do those theme updates and give us developers a heads up, so that we won't work on the live-site during that time.

> If you want to see the new theme before applying to the CSIS we can schedule a telco to show you a demo, or wait for the next developers telco, up to you!

We could rather have a telco after the new theme has been applied in order to find out what could be further improved.

**Comment by DanielRodera** [comment]
Ok @patrickkaleta, Alejandro will work on the new CSIS theme, **next Tuesday (25th).** 

I will let you know when the theme be available.

**Comment by p-a-s-c-a-l** [comment]
New Theme repository: https://github.com/clarity-h2020/clarity-theme
So this repository becomes obsolete.
